spring:
  datasource:
    url: jdbc:mysql://localhost:3306/autohealx_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: autohealx_dev
    password: dev123
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.autohealx: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

autohealx:
  healing:
    health-check-interval: 10000  # 10 seconds for faster development
  chaos:
    enabled: true  # Enable for testing

server:
  port: 8080