spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    
  data:
    redis:
      host: localhost
      port: 6379
      
  flyway:
    enabled: false

logging:
  level:
    com.autohealx: WARN
    org.springframework: WARN
    org.hibernate: WARN

autohealx:
  healing:
    enabled: true
    health-check-interval: 5000  # 5 seconds for tests
  ai:
    enabled: false  # Disable AI for unit tests
  chaos:
    enabled: false