spring:
  application:
    name: autohealx
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:mysql://localhost:3306/autohealx?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: autohealx
    password: autohealx123
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: AutoHealX-DB-Pool
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        generate_statistics: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2

  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,beans,env,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      sla:
        http.server.requests: 100ms, 500ms, 1s, 2s, 5s

# Logging Configuration
logging:
  level:
    com.autohealx: INFO
    com.autohealx.healing: DEBUG
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/autohealx.log
    max-size: 100MB
    max-history: 30

# AutoHealX Specific Configuration
autohealx:
  healing:
    enabled: true
    health-check-interval: 30000  # 30 seconds
    max-healing-attempts: 3
    healing-cooldown-minutes: 5
    
  ai:
    enabled: true
    prediction-threshold: 0.7
    confidence-threshold: 0.8
    
  chaos:
    enabled: false  # Disabled by default
    
  monitoring:
    enabled: true
    metrics-retention-days: 30

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
  http2:
    enabled: true